
package client.Screens;

/**
 * Class that displays the welcome screen blurb to the user.
 */
public class WelcomeScreen extends javax.swing.JPanel {

    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        blurb = new javax.swing.JLabel();
        blurb1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 255));

        title.setFont(new java.awt.Font("Lantinghei SC", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Welcome to  BookBnB");

        blurb.setFont(new java.awt.Font("Lantinghei SC", 0, 18)); // NOI18N
        blurb.setForeground(new java.awt.Color(255, 255, 255));
        blurb.setText("<html>BookBnB is a peer to peer book lending platform <br> which allows users in a local area to publish and share books with one another.");

        blurb1.setFont(new java.awt.Font("Lantinghei SC", 1, 18)); // NOI18N
        blurb1.setForeground(new java.awt.Color(255, 255, 255));
        blurb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blurb1.setText("Please register or login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 134, Short.MAX_VALUE)
                .addComponent(blurb, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(blurb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(title)
                .addGap(26, 26, 26)
                .addComponent(blurb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blurb1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blurb;
    private javax.swing.JLabel blurb1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
