import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class MainScreen {

    private JFrame frame;
    private JPanel homeScreen;
    private JTable yourBooksTable;
    private JTabbedPane tabbedPane1;
    private JPanel menuBar;
    private JPanel tabPane;
    private JScrollPane yourBooks;
    private JScrollPane browseBooks;
    private JTable browseBooksTable;
    private JLabel welcomeTxt;
    private JPanel Buttons;
    private JButton addBookBtn;

    public MainScreen(JFrame loginFrame) {
        frame = new JFrame("BookBnB");

        frame.setContentPane(homeScreen);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //frame.pack();
        frame.setSize(600, 300);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        loginFrame.setVisible(false);

        welcomeTxt.setText("Welcome " + Controller.email + " to BookBnB!");

        setupListeners();

        populateTable();

    }

    private void setupListeners() {
        addBookBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AddBook addBookDialog = new AddBook(frame);
                addBookDialog.setVisible(true);
            }
        });
    }


    private void populateTable() {

        Book book1 = new Book("1234", "test", "hello world");
        Book book2 = new Book("4567", "JKRowling", "Harry Potter");

        ArrayList<Book> books = new ArrayList<Book>();

        books.add(book1);
        books.add(book2);

        TableModel tableModel = new TableModel(books);

        yourBooksTable.setModel(tableModel);
        yourBooksTable.setAutoCreateRowSorter(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        homeScreen = new JPanel();
        homeScreen.setLayout(new GridBagLayout());
        menuBar = new JPanel();
        menuBar.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        homeScreen.add(menuBar, gbc);
        welcomeTxt = new JLabel();
        welcomeTxt.setText("Welcome Username");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        menuBar.add(welcomeTxt, gbc);
        tabPane = new JPanel();
        tabPane.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        homeScreen.add(tabPane, gbc);
        tabbedPane1 = new JTabbedPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        tabPane.add(tabbedPane1, gbc);
        yourBooks = new JScrollPane();
        tabbedPane1.addTab("Your Books", yourBooks);
        yourBooksTable = new JTable();
        yourBooks.setViewportView(yourBooksTable);
        browseBooks = new JScrollPane();
        tabbedPane1.addTab("Browse Books", browseBooks);
        browseBooksTable = new JTable();
        browseBooks.setViewportView(browseBooksTable);
        Buttons = new JPanel();
        Buttons.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        homeScreen.add(Buttons, gbc);
        addBookBtn = new JButton();
        addBookBtn.setText("Add Book");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Buttons.add(addBookBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return homeScreen;
    }

    class TableModel extends AbstractTableModel {

        private ArrayList<Book> books;
        String headers[] = new String[]{"Title", "Author", "ISBN"};

        public TableModel(ArrayList<Book> books) {
            this.books = books;
        }

        @Override
        public int getRowCount() {
            return books.size();
        }

        @Override
        public int getColumnCount() {
            return 3;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {

            Book book = books.get(rowIndex);

            switch (columnIndex) {
                case 0:
                    return book.getTitle();
                case 1:
                    return book.getAuthor();
                case 2:
                    return book.getISBN();
                default:
                    return "";
            }

        }

        @Override
        public String getColumnName(int column) {
            return headers[column];
        }
    }

}
